/**
 * nativeFileBridge.js
 * ---------------------
 * Blobs generated by jsPDF/ExcelJS need different handling on native
 * Android (via Capacitor Filesystem + Share plugins) vs. a plain
 * browser (plain download link). This module abstracts that so feature
 * code never has to branch on platform.
 */

function blobToBase64(blob) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result.split(',')[1]);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

/**
 * Saves a blob to device storage and opens the native share sheet so the
 * factory owner can send it via WhatsApp, email, or save to Drive.
 * `mimeType` (optional) re-wraps the blob with an explicit content type —
 * some Android share targets route incorrectly without one.
 */
export async function saveAndShareBlob(blob, filename, mimeType, text = '') {
  const isNative = !!(window.Capacitor && window.Capacitor.isNativePlatform?.());
  const typedBlob = mimeType && blob.type !== mimeType ? new Blob([blob], { type: mimeType }) : blob;

  if (!isNative) {
    // Web fallback — plain browser download
    const url = URL.createObjectURL(typedBlob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
    return { method: 'browser-download' };
  }

  const { Filesystem, Directory } = await import('@capacitor/filesystem');
  const { Share } = await import('@capacitor/share');

  const base64Data = await blobToBase64(typedBlob);

  const result = await Filesystem.writeFile({
    path: filename,
    data: base64Data,
    directory: Directory.Cache,
  });

  const shareOptions = {
    title: filename,
    url: result.uri,
    dialogTitle: `Share ${filename}`,
  };
  if (text) {
    shareOptions.text = text;
  }

  await Share.share(shareOptions);

  return { method: 'native-share', uri: result.uri };
}

/** Light haptic tap feedback for confirm actions — degrades gracefully on web. */
export async function hapticTap() {
  try {
    const { Haptics, ImpactStyle } = await import('@capacitor/haptics');
    await Haptics.impact({ style: ImpactStyle.Light });
  } catch {
    /* no-op on web */
  }
}
